### PR TITLE
Fixing contract for updated models.

### LINKED ISSUE #14: NPI Rest API Unnotified Changes
The NPPES NPI Rest API was changed without warning.  Unfortunately some of these changes were breaking and were not versioned appropriately, changes being:

1. `result_count` field was renamed to `resultCount`
2. Timestamps/dates were being returned as seconds from the epoch, now they are returned in milliseconds from the epoch

Other changes:
1. Older versions of the NPI API have now been deprecated and removed

### PR DESCRIPTION
**Pull request by dustinmiller01**
Contract changed, result_count now resultCount 
Time Conversion, seems to be different, need to verify intent.

### CODE REVIEW

**Comment by ghost1face** [comment]
Well this is a breaking change. Even worse that the destination API seemed to have introduced breaking changes and had not versioned accordingly

**Comment by dustinmiller01** [comment]
> Well this is a breaking change. Even worse that the destination API seemed to have introduced breaking changes and had not versioned accordingly

Yup, was going to discuss with you Monday

**Comment by ghost1face** [comment]
It's a good fix, but the abrupt change makes me worried of other changes or reversions that could happen in the near future.  I think we should look to be compatible both ways unfortunately

**Comment by ghost1face** [comment]
After an internal discussion we will close this one in favor of #15

**Pull request closed without merging**
